import { CANDIDATES, TOPICS, REVIEW_DATE, ROSTER_URL, DOCUMENT_NOTES } from './candidates-data.mjs';
import { FEATURED_ORDER, OVERVIEWS } from './candidate-overviews.mjs';
export const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const e=escapeHtml;
const external=(url,label)=>`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} ↗</a>`;
const pageLink=(c,p)=>external(c.planUrl,`Plano completo · p. ${p.pages}`);
const identity=c=>`<span class="candidate-record">${e(c.party)} · urna ${c.number}</span><h3>${e(c.name)}</h3>`;
function legacyAnchor(id){return ({lula:'scene-lula',flavio_bolsonaro:'scene-flavio',zema:'scene-zema',caiado:'scene-caiado',renan_santos:'scene-renan',augusto_cury:'scene-cury'})[id]||`scene-${id}`;}

export function directoryHtml(){
 const featured=FEATURED_ORDER.map(id=>CANDIDATES.find(c=>c.id===id));
 return `<section id="scene-candidatos" class="scene candidate-editorial candidate-introduction" aria-labelledby="candidates-title"><header class="candidate-section-heading"><span class="candidate-eyebrow">Quem são os candidatos</span><h2 id="candidates-title">Conheça quem está<br>disputando a Presidência.</h2><p>Veja a apresentação de cada candidato: trajetória, características do programa e propostas principais. Para aprofundar, entre na página individual.</p><nav class="candidate-jump-links" aria-label="Ir para um candidato">${featured.map(c=>`<a href="#${legacyAnchor(c.id)}">${e(c.name)}</a>`).join('')}<a href="#scene-outras-candidaturas">Outras candidaturas</a></nav></header></section>
 ${featured.map(candidateSceneHtml).join('\n')}
 <section id="scene-outras-candidaturas" class="scene candidate-editorial candidate-additional" aria-labelledby="other-candidates-title"><h2 id="other-candidates-title">Outras candidaturas</h2><p>A página de planos do TSE lista 13 candidaturas. Além dos seis capítulos acima, os outros sete perfis estão disponíveis aqui e no comparador.</p><details class="candidate-method"><summary>Ver as outras sete candidaturas e seus planos</summary><div class="candidate-additional-list">${CANDIDATES.filter(c=>!FEATURED_ORDER.includes(c.id)).map(c=>`<article class="candidate-directory-card"><div>${identity(c)}</div><p>${e(c.topics.economia.summary)}</p><a class="candidate-action" href="${c.id}.html">Conhecer o plano de ${e(c.name)} ↗</a></article>`).join('')}</div></details><p class="candidate-source">${external(ROSTER_URL,'Conferir a lista no TSE')} · A inclusão na lista de planos não substitui a consulta à situação do registro eleitoral.</p>${methodHtml()}</section>`;
}

function candidateSceneHtml(c){const o=OVERVIEWS[c.id];return `<section id="${legacyAnchor(c.id)}" class="scene candidate-scene candidate-presentation" aria-labelledby="candidate-title-${c.id}">
 <div class="candidate-header"><div class="candidate-avatar"><div class="candidate-avatar-inner"><img src="assets/${o.photo}" alt="${e(o.name)}" loading="lazy" width="260" height="300"></div></div><div class="candidate-meta"><span class="candidate-eyebrow">Apresentação do candidato</span><h2 class="candidate-name" id="candidate-title-${c.id}">${e(o.name)}</h2><div class="candidate-partido-badge">${e(c.party)} · Urna ${c.number}</div><div class="candidate-info-row"><span class="candidate-info-item">${e(o.role)}</span></div><div class="candidate-info-row"><span class="candidate-info-item">Experiência: ${e(o.experience)}</span></div></div></div>
 <div class="candidate-presentation-content"><h3 class="candidate-section-title">Quem é</h3><p class="candidate-bio">${e(o.bio)}</p><p class="candidate-source">${o.sources.map(([label,url])=>external(url,label)).join(' · ')}</p>
 <h3 class="candidate-section-title">Características do programa</h3><div class="candidate-traits">${o.traits.map(([title,text])=>`<div><h4>${e(title)}</h4><p>${e(text)}</p></div>`).join('')}</div><p class="candidate-source">Síntese das posições do programa; não é avaliação da personalidade ou nota de viabilidade. ${external(c.indexUrl,'Fonte: índice do TSE')}</p>
 <h3 class="candidate-section-title">Propostas principais por tema</h3><div class="propostas-grid">${Object.entries(TOPICS).map(([key,t])=>`<div class="proposta-card visible"><div class="proposta-tema">${t.name}</div><p class="proposta-desc">${e(c.topics[key].summary)}</p></div>`).join('')}</div>
 <a class="btn-magnetic btn-saiba-mais candidate-more" href="${c.id}.html"><span>Saiba mais sobre ${e(o.name)}</span><span class="btn-magnetic-icon-wrapper" aria-hidden="true">↗</span></a><p class="candidate-more-description">Na página do candidato: explicações, contrapontos, limites e fontes de cada proposta.</p></div></section>`;}

export function methodHtml(){return `<details class="candidate-method" id="metodo-candidatos"><summary>Como ler esta comparação e quais são seus limites</summary><div>
<p><strong>Proposta documentada:</strong> resumo atribuído ao plano a partir do índice temático do TSE. Os links mostram o índice e o documento completo, com a página indicada. O projeto não verificou integralmente todos os planos.</p>
<p><strong>Análise do projeto:</strong> mecanismos possíveis, limites, interpretações alternativas e indicadores para acompanhar. São inferências e perguntas de avaliação, não declarações do candidato nem prova de que a proposta funcionará.</p>
<p><strong>Custo, receita, prazo e dependências:</strong> ainda não há auditoria completa ou simulação independente. “Não auditado” não significa “não consta no plano”. Passagens adicionais lidas diretamente no PDF são identificadas nos perfis.</p>
<p><strong>Mesmos critérios:</strong> quatro temas para todas as 13 candidaturas; seletores em ordem alfabética, sem nota de ideologia, ranking de viabilidade ou recomendação de voto. A página principal preserva os seis capítulos de apresentação originais; outras sete candidaturas estão na seção adicional. Os recortes não representam a totalidade nem a ordem de prioridade dos programas.</p>
<p><strong>Pesquisas, declarações e controvérsias:</strong> os percentuais estimados e as antigas checagens sem documentação suficiente foram retirados. Esta revisão não apresenta um levantamento auditado desses itens. Pesquisas exigem documento, campo, amostra, margem, cenário e registro; controvérsias exigem documentos e situação processual, distinguindo alegação de decisão.</p>
<p><strong>Fonte e atualização:</strong> ${external(ROSTER_URL,'Página de planos do TSE')} · consulta em ${REVIEW_DATE}. A publicação no TSE comprova a origem do programa; não é endosso à viabilidade ou à veracidade de todas as afirmações. Para o registro, ${external('https://divulgacandcontas.tse.jus.br/divulga/','consulte o DivulgaCandContas')}.</p>
<p><a href="dados/candidatos-2026-10-02.json" download>Baixar os recortes e suas referências (JSON)</a></p></div></details>`;}

function documentNote(c,key){const note=DOCUMENT_NOTES[c.id];if(!note||note.topic!==key)return '';return `${e(note.text)} <span class="candidate-source">${external(c.planUrl,`Passagem do PDF · p. ${note.pages}`)}</span>`;}

export function comparisonHtml(a,b,key){const t=TOPICS[key];const rows=[
['Proposta documentada',c=>`<p>${e(c.topics[key].summary)}</p><p class="candidate-source">${pageLink(c,c.topics[key])} · ${external(c.indexUrl,'Índice do TSE')}</p>`],
['Como pode funcionar',c=>`<p>${e(c.topics[key].mechanism)}</p>`],
['Limites a conferir',c=>`<p>${e(c.topics[key].limits)}</p>`],
['Interpretação alternativa',c=>`<p>${e(c.topics[key].alternative)}</p>`],
['Custeio e prazo',c=>`<p>${documentNote(c,key)||'Não auditados neste recorte. Consulte o plano para conferir custo inicial e recorrente, receita ou compensação, prazo e hipóteses. A falta dessa auditoria não prova ausência de detalhamento no documento.'}</p>`],
['Conclusão permitida',c=>`<p>${e(c.topics[key].conclusion)}</p><a href="${c.id}.html#proposta-${key}">Ler o ciclo completo de ${e(c.name)} ↗</a>`]
];return `<article class="comparison-reading" aria-labelledby="comparison-question"><header class="comparison-question"><span class="candidate-eyebrow">Pergunta · ${t.name}</span><h3 id="comparison-question">${e(t.question)}</h3></header>
<div class="compare-evidence"><h4>Dados comparáveis para julgar resultados</h4><p>${e(t.evidence)}</p><a href="index.html#${t.anchor}">Consultar os indicadores e suas fontes ↗</a></div>
<div class="compare-identities">${[a,b].map((c,i)=>`<div><span class="candidate-eyebrow">Candidatura ${i?'B':'A'}</span>${identity(c)}</div>`).join('')}</div>
${rows.map(([label,render])=>`<section class="compare-row"><h4>${label}${['Proposta documentada','Custeio e prazo'].includes(label)?'':' <span class="analysis-label">Análise do projeto</span>'}</h4><div class="compare-pair">${[a,b].map((c,i)=>`<div class="compare-cell"><span class="compare-mobile-name">${i?'B':'A'} · ${e(c.name)}</span>${render(c)}</div>`).join('')}</div></section>`).join('')}
<details class="candidate-method"><summary>Dependências e indicadores para acompanhar ambos</summary><div><p>${e(t.execution)}</p><p><strong>Medir:</strong> ${e(t.measure)}</p><p>${e(t.interpretation)}</p></div></details></article>`;}

export function compareHtml(){const options=selected=>CANDIDATES.map(c=>`<option value="${c.id}"${c.id===selected?' selected':''}>${e(c.name)} · ${e(c.party)}</option>`).join('');return `<section id="scene-encerramento" class="scene candidate-editorial" aria-labelledby="compare-title"><header class="candidate-section-heading"><span class="candidate-eyebrow">Comparador por tema</span><h2 id="compare-title">A mesma pergunta.<br>Dois caminhos para avaliar.</h2><p>Escolha o tema e as candidaturas. Leia a proposta, a explicação e o contraponto antes de tirar uma conclusão.</p></header>
<div class="candidate-comparator" data-candidate-comparator><fieldset class="compare-controls"><legend>Escolhas da comparação</legend><label>Tema<select id="compare-topic" disabled>${Object.entries(TOPICS).map(([key,t])=>`<option value="${key}">${t.name}</option>`).join('')}</select></label><label>Candidatura A<select id="compare-a" disabled>${options(CANDIDATES[0].id)}</select></label><label>Candidatura B<select id="compare-b" disabled>${options(CANDIDATES[1].id)}</select></label></fieldset><p class="candidate-source">A seleção inicial segue a ordem alfabética. O comparador não atribui pontuação.</p><p class="sr-only" id="compare-status" role="status" aria-live="polite" aria-atomic="true"></p><div id="compare-result">${comparisonHtml(CANDIDATES[0],CANDIDATES[1],'economia')}</div><button class="candidate-action compare-copy" type="button" hidden>Copiar link desta comparação</button><noscript><p>Os seletores precisam de JavaScript. A comparação inicial está disponível acima e todos os <a href="#scene-candidatos">13 perfis</a> podem ser lidos normalmente.</p></noscript></div></section>`;}

export function profileHtml(c){const overview=OVERVIEWS[c.id];return `<main id="candidato-main" class="candidate-profile"><header class="profile-header">${overview?`<img class="profile-portrait" src="assets/${overview.photo}" alt="${e(overview.name)}" width="150" height="180">`:""}<span class="candidate-eyebrow">Plano documentado · consulta de ${REVIEW_DATE}</span><p class="candidate-record">${e(c.party)} · urna ${c.number}</p><h1>${e(c.name)}</h1>${overview?`<p class="candidate-record">${e(overview.role)}</p><p>${e(overview.bio)}</p><p class="candidate-source">${overview.sources.map(([label,url])=>external(url,label)).join(" · ")}</p>`:""}<p>Quatro temas, os mesmos critérios. Propostas atribuídas ao documento oficial e interpretações identificadas como análise do projeto.</p><p class="candidate-source">${external(c.indexUrl,'Índice temático do TSE')} · ${external(c.planUrl,'Abrir o plano completo')}</p><a class="candidate-action" href="index.html?candidatoA=${c.id}#scene-encerramento">Comparar esta candidatura por tema ↗</a></header><nav class="profile-topics" aria-label="Temas do perfil">${Object.entries(TOPICS).map(([key,t])=>`<a href="#proposta-${key}">${t.name}</a>`).join('')}</nav>
${Object.entries(TOPICS).map(([key,t])=>{const p=c.topics[key];return `<article class="proposal-cycle" id="proposta-${key}" aria-labelledby="title-${key}"><header><span class="candidate-eyebrow">1 · Pergunta · ${t.name}</span><h2 id="title-${key}">${e(t.question)}</h2></header>
<section class="proposal-step"><h3>2 · Proposta e dados comparáveis</h3><p class="evidence-badge">Proposta documentada · síntese do índice do TSE</p><p class="proposal-summary">${e(p.summary)}</p><p class="candidate-source">${pageLink(c,p)} · ${external(c.indexUrl,'Conferir o índice')}</p><p><strong>Para comparar resultados:</strong> ${e(t.evidence)}</p><a href="index.html#${t.anchor}">Ler os dados históricos e suas definições ↗</a></section>
<section class="proposal-step"><h3>3 · Explicação <span class="analysis-label">Análise do projeto</span></h3><p>${e(p.mechanism)}</p><details><summary>Quem executa e como medir</summary><p>${e(t.execution)}</p><p><strong>Indicadores:</strong> ${e(t.measure)}</p></details></section>
<section class="proposal-step"><h3>4 · Interpretação alternativa <span class="analysis-label">Análise do projeto</span></h3><p>${e(p.alternative)}</p><p><strong>Limite a testar:</strong> ${e(p.limits)}</p><details><summary>O que pode confundir a avaliação</summary><p>${e(t.interpretation)}</p></details></section>
<section class="proposal-step proposal-conclusion"><h3>5 · Conclusão que a fonte permite</h3><p>${e(p.conclusion)}</p></section>
<details class="candidate-method"><summary>Custo, receita, prazo e documentação adicional</summary><div>${documentNote(c,key)?`<p>${documentNote(c,key)}</p>`:''}<p><strong>Situação da auditoria:</strong> custo total, fonte de receita, cronograma e compatibilidade jurídica ainda não auditados de forma completa. Este recorte não permite dizer que o plano deixa de informar esses itens.</p><ul><li>Separar investimento inicial de manutenção e pessoal.</li><li>Conferir receita permanente, realocação de gastos, dívida e venda de ativos.</li><li>Verificar se o prazo está dentro do mandato e quais aprovações são necessárias.</li><li>Identificar hipóteses e projeções do candidato e distinguir essas estimativas de resultado observado.</li></ul></div></details></article>`;}).join('')}${methodHtml()}<a class="candidate-action" href="index.html#scene-candidatos">Voltar às 13 candidaturas ←</a></main>`;}

export function initComparator(){const root=document.querySelector('[data-candidate-comparator]');if(!root)return;const topic=root.querySelector('#compare-topic'),a=root.querySelector('#compare-a'),b=root.querySelector('#compare-b'),params=new URLSearchParams(location.search);const valid=id=>CANDIDATES.some(c=>c.id===id);
if(valid(params.get('candidatoA')))a.value=params.get('candidatoA');if(valid(params.get('candidatoB')))b.value=params.get('candidatoB');if(Object.hasOwn(TOPICS,params.get('tema')))topic.value=params.get('tema');
const update=(changed,writeUrl=true)=>{if(a.value===b.value){const other=changed===b?a:b;other.value=CANDIDATES.find(c=>c.id!==changed.value).id;}const ca=CANDIDATES.find(c=>c.id===a.value),cb=CANDIDATES.find(c=>c.id===b.value);root.querySelector('#compare-result').innerHTML=comparisonHtml(ca,cb,topic.value);root.querySelector('#compare-status').textContent=`${TOPICS[topic.value].name}: ${ca.name} e ${cb.name}. Comparação atualizada.`;if(writeUrl){const url=new URL(location.href);url.searchParams.set('candidatoA',ca.id);url.searchParams.set('candidatoB',cb.id);url.searchParams.set('tema',topic.value);history.replaceState(null,'',url);}};
for(const control of [topic,a,b]){control.disabled=false;control.addEventListener('change',()=>update(control));}update(a,false);const copy=root.querySelector('.compare-copy');copy.hidden=false;copy.addEventListener('click',async()=>{update(a);const url=new URL(location.href);url.hash='scene-encerramento';try{await navigator.clipboard.writeText(url.href);root.querySelector('#compare-status').textContent='Link da comparação copiado.';copy.textContent='Link copiado';}catch{root.querySelector('#compare-status').textContent='Copie o endereço da página para compartilhar esta comparação.';copy.textContent='Copie o endereço da página';}setTimeout(()=>copy.textContent='Copiar link desta comparação',2500);});}
