// Fonte das propostas: índice temático do TSE, consultado em 02/10/2026.
// Mecanismos, contrapontos e perguntas de implementação são análises do projeto.
export const REVIEW_DATE = '02/10/2026';
const BASE = 'https://www.tse.jus.br/eleicoes/eleicoes-2026-content/propostas-de-governo-dos-candidatos-ao-cargo-de-presidente-da-republica-eleicoes-2026/';
export const ROSTER_URL = BASE + 'planos-de-governo-dos-candidatos-ao-cargo-de-presidente-da-republica-eleicoes-2026';
export const TOPICS = {
  economia: {
    name: 'Economia', question: 'Como ampliar renda e emprego sem comprometer o financiamento dos serviços?',
    anchor: 'economia-contas',
    evidence: 'Compare renda mediana real, emprego formal, participação e subutilização, investimento, resultado primário e dívida/PIB. A média salarial e a taxa de desemprego, sozinhas, não descrevem a situação de todas as famílias.',
    interpretation: 'Uma política pode estimular a demanda no curto prazo e elevar despesas permanentes. Outra pode reduzir gastos e afetar serviços ou atividade. Juros, produtividade e conjuntura também influenciam os resultados; não basta atribuir tudo ao presidente.',
    measure: 'Renda mediana real e formalização, junto com investimento, inflação e trajetória fiscal. Fixar ano-base, prazo, distribuição por renda e região e cenário sem a medida.',
    execution: 'Mudanças tributárias, trabalhistas e fiscais podem exigir leis ou emendas constitucionais e negociação com o Congresso. Avaliar também o efeito sobre empresas, famílias, estados e municípios.'
  },
  saude: {
    name: 'Saúde', question: 'A proposta reduz a espera e melhora o cuidado, ou apenas aumenta a oferta anunciada?',
    anchor: 'saude-acesso',
    evidence: 'Compare tempo de espera por especialidade e região, demanda atendida e reprimida, cobertura de atenção primária e resultados de saúde. Contar consultas ou hospitais não informa, sozinho, se o paciente conseguiu tratamento no prazo.',
    interpretation: 'Mais atendimentos podem refletir maior acesso, maior demanda ou repetição de procedimentos. Uma fila pode crescer depois que pessoas antes excluídas entram no sistema. Compare capacidade, necessidade e continuidade do cuidado.',
    measure: 'Mediana e percentil 90 do tempo de espera, por especialidade e região; cobertura e desfechos. Informar tamanho da fila, entradas e saídas e custo por atendimento resolvido.',
    execution: 'O SUS envolve União, estados e municípios. Equipamentos precisam de profissionais, manutenção e custeio; ampliação de vagas depende também de regulação, transporte e integração da rede.'
  },
  educacao: {
    name: 'Educação', question: 'Como transformar acesso e permanência em aprendizagem efetiva?',
    anchor: 'educacao-internacional',
    evidence: 'Compare alfabetização, aprendizagem em matemática e leitura, abandono e conclusão por região e renda. No Ideb, observe separadamente desempenho e aprovação. No PISA, confira a nota do Brasil e a mudança da referência internacional.',
    interpretation: 'Mais matrículas ou aprovações não garantem aprendizagem. Uma posição internacional melhor pode vir de queda de outros países. Mudanças na composição dos alunos e na participação nas provas também afetam comparações.',
    measure: 'Aprendizagem em avaliações comparáveis, alfabetização, abandono e conclusão, com recorte de vulnerabilidade. Publicar cobertura das avaliações e evitar comparar escalas ou etapas diferentes.',
    execution: 'A educação básica depende principalmente de redes municipais e estaduais. A União precisa combinar apoio financeiro, formação, currículo e avaliação com a capacidade de execução dessas redes.'
  },
  seguranca: {
    name: 'Segurança', question: 'Como reduzir violência e crime organizado com resultados verificáveis?',
    anchor: 'seguranca-tendencia',
    evidence: 'Compare mortes violentas por 100 mil habitantes, feminicídios, letalidade policial, desaparecimentos e esclarecimento de crimes. Use séries e definições iguais; médias nacionais podem esconder pioras estaduais.',
    interpretation: 'Menos registros podem significar menos crimes ou menos notificações. A queda de homicídios não demonstra redução de todos os crimes nem o efeito isolado de uma medida. Operações e prisões são atividades, não prova de redução duradoura da violência.',
    measure: 'Taxas de violência e esclarecimento, reincidência e controle de facções, com recortes estaduais e avaliação de direitos e qualidade dos registros. Comparar períodos e territórios equivalentes.',
    execution: 'A maior parte do policiamento é estadual. Coordenação federal, investigação financeira e prisões exigem integração; alterações penais ou de instituições dependem do Congresso e de compatibilidade constitucional.'
  }
};

// Cada recorte: síntese atribuída ao plano; páginas indicadas pelo TSE;
// mecanismo possível; limite a testar; interpretação alternativa.
const records = [
  ['clariana_barao','Clariana Barão','DC',27,'clariana-barao-propostas-de-governo','plano-de-governo-1',{
    economia: ['Revisão de gastos e subsídios, crédito e capacitação para pequenos negócios e infraestrutura com parcerias público-privadas.','5–6','Revisar despesas pode abrir espaço orçamentário; crédito e capacitação procuram reduzir barreiras à expansão de pequenos negócios.','É preciso separar economia recorrente de receita temporária e conferir custo do crédito, inadimplência e obrigações futuras das parcerias.','Crédito sem demanda ou produtividade pode aumentar dívida empresarial. Simplificar regras e melhorar infraestrutura também pode apoiar negócios.'],
    saude: ['Atenção primária mais resolutiva, prevenção e telemedicina com organização digital das filas.','11–12','Tratar problemas na atenção primária e organizar encaminhamentos pode evitar procedimentos desnecessários e acelerar o atendimento adequado.','Digitalização precisa de equipes, conectividade e vagas efetivas. Medir a espera após o encaminhamento, não somente a marcação da consulta.','Uma rede presencial bem equipada pode ser decisiva onde falta internet; telemedicina complementa, mas não substitui todos os exames.'],
    educacao: ['Alfabetização, recuperação da aprendizagem, formação e carreira docente, primeira infância e ensino técnico.','7–8','Formação e recuperação procuram corrigir dificuldades acumuladas; creches e ensino técnico atuam em etapas diferentes da trajetória escolar.','Conferir calendário, capacidade das redes, seleção dos professores e metas de aprendizagem; matrícula em curso técnico não garante emprego.','Apoio individual e permanência escolar podem produzir ganhos mesmo sem expansão de novas unidades; avaliar custo e resultado por aluno.'],
    seguranca: ['Integração de inteligência, rastreamento financeiro do crime e trabalho e educação no sistema prisional.','9–10','A investigação patrimonial procura cortar recursos das organizações; educação e trabalho na prisão procuram apoiar a reinserção.','Conferir integração de dados, equipes de investigação e acompanhamento dos egressos; apreensão de bens não equivale automaticamente a menos violência.','Prevenção territorial e esclarecimento de homicídios podem complementar a repressão financeira; comparar resultados de cada frente.']
  }],
  ['edmilson_costa','Edmilson Costa','PCB',21,'edmilson-costa-propostas-de-governo','proposta-pcb',{
    economia: ['Jornada de 30 horas sem redução salarial, tributação progressiva, estatização bancária e suspensão e auditoria dos juros da dívida.','2, 4–5, 14','Redistribuição de renda e reorganização do crédito buscam alterar a divisão dos recursos e das horas de trabalho.','Medir produtividade, custo do trabalho, oferta de crédito e efeito da suspensão sobre refinanciamento, juros e segurança dos contratos.','Reduzir jornadas pode gerar contratações ou reorganização da produção; o efeito depende de demanda, produtividade e custo, não apenas da lei.'],
    saude: ['Sistema integralmente público, fim de organizações sociais e destinação de 10% do PIB à saúde.','6, 10','Ampliar financiamento e gestão pública procura aumentar capacidade de atendimento e reduzir dependência de prestadores privados.','A meta de gasto é uma proposta, não verba disponível. Conferir receita, transição dos contratos e profissionais para manter os serviços.','Gasto maior pode ampliar acesso ou financiar estruturas pouco resolutivas. Comparar qualidade e custo sob diferentes formas de gestão.'],
    educacao: ['Ensino público e gratuito em todas as etapas, estatização do ensino privado, expansão técnica e valorização docente.','2, 7, 10','Expansão da rede pública procura absorver a demanda e reduzir a dependência do pagamento direto pelas famílias.','Dimensionar vagas, pessoal, patrimônio e custeio da transição; comparar aprendizagem e permanência, além do tamanho da rede.','Acesso público pode ser ampliado por diferentes combinações de expansão e financiamento. Avaliar qual preserva qualidade e atendimento durante a transição.'],
    seguranca: ['Desmilitarização e unificação das polícias, mudança da política de drogas e serviços públicos nos territórios.','6, 12–13','Reorganização policial e prevenção territorial procuram alterar incentivos, coordenação e relação entre polícia e população.','Reforma institucional exige transição, treinamento e controle externo. Conferir efeito sobre investigação, violência e proteção das comunidades.','Mudanças administrativas não garantem menos crimes; integração e investigação podem melhorar também sob outras estruturas policiais.']
  }],
  ['augusto_cury','Escritor Augusto Cury','AVANTE',70,'escritor-augusto-cury-propostas-de-governo','proposta-avante',{
    economia: ['Redução gradual da dívida, déficit próximo de zero, eficiência do gasto, simplificação tributária e apoio ao empreendedor.','36–39, 42','Eficiência e simplificação procuram reduzir desperdícios e custos; crédito ao empreendedor busca ampliar investimento e atividade.','Conferir quais despesas e tributos mudam, compensações de receita e risco do crédito. Déficit precisa de definição e ano-base.','Um equilíbrio obtido com receita temporária difere de ajuste permanente. Comparar também o efeito sobre investimento e serviços.'],
    saude: ['Saúde mental e emocional, atenção primária e preventiva e expansão da telessaúde.','44–45, 161–164','Prevenção e cuidado próximo ao paciente procuram reduzir agravamentos e ampliar acesso antes de recorrer ao hospital.','Conferir protocolos, formação das equipes e integração entre saúde mental, atenção básica e especialistas; alcance anunciado não prova efetividade clínica.','Intervenções diferentes precisam de evidência específica. Não transferir para um programa inteiro resultados de uma técnica ou experiência isolada.'],
    educacao: ['Alfabetização, educação emocional, ensino médio ligado ao trabalho e formação empreendedora.','43–44, 68, 75','A proposta combina aprendizagem básica, habilidades socioemocionais e preparação para trajetórias profissionais.','Avaliar cada componente com instrumentos adequados; satisfação com aulas e autoestima não substituem aprendizagem em leitura e matemática.','Habilidades emocionais podem complementar a aprendizagem; não demonstram, sozinhas, que mudanças curriculares elevarão o desempenho acadêmico.'],
    seguranca: ['Ministério da Segurança, programas FOCO e FATO, enfrentamento financeiro das facções e reinserção prisional.','45–47, 186–189','Coordenação e foco territorial procuram combinar repressão ao crime organizado e prevenção e reinserção.','Conferir atribuições e orçamento dos programas, integração estadual e avaliação de reincidência; criar uma estrutura não demonstra resultado.','Coordenação pode melhorar pela reorganização de órgãos existentes ou por um ministério; comparar capacidade operacional e custo de ambas.']
  }],
  ['flavio_bolsonaro','Flávio Bolsonaro','PL',22,'flavio-bolsonaro','proposta-pl',{
    economia: ['Reformular regras fiscais para estabilizar e reduzir a dívida, limitar crédito subsidiado e criar um banco nacional de vagas.','43–44, 70–71','Controle de despesas procura reduzir pressão fiscal; a intermediação de vagas procura aproximar empresas e pessoas à procura de trabalho.','Uma plataforma não cria demanda por trabalhadores. Conferir gastos atingidos, proteção dos serviços e hipóteses para queda da dívida.','A dívida depende também de juros e crescimento. Melhor intermediação ajuda quem procura emprego, mas precisa alcançar também os desalentados.'],
    saude: ['Prontuário digital, telessaúde, uso de capacidade privada disponível e correção da tabela do SUS.','25–26, 37–39','Integração dos registros e contratação de capacidade procuram ampliar atendimento e reduzir repetição de exames e gargalos.','Conferir preço dos contratos, critérios de qualidade, segurança dos dados e disponibilidade regional; reajustar valores não garante vagas novas.','O gargalo pode estar no encaminhamento ou na falta de especialistas, e não apenas no pagamento. Comparar essas causas antes de expandir contratos.'],
    educacao: ['Alfabetização fônica, formação docente, ensino técnico, tempo integral e modelos cívico-militares.','34–37','Mudanças no ensino, na formação e no tempo de permanência procuram melhorar a aprendizagem e a preparação profissional.','Separar o efeito do método e da gestão do perfil dos alunos e dos recursos; comparar escolas equivalentes, sem selecionar somente bons resultados.','Mais horas e disciplina podem ajudar ou não; formação, materiais e apoio a alunos com dificuldade também interferem no desempenho.'],
    seguranca: ['Combate a facções, controle de fronteiras, mudanças penais, presídios e reconhecimento facial.','13–16','Repressão coordenada e restrição à atuação de facções procuram reduzir capacidade criminal e circulação de armas e drogas.','Endurecimento penal exige exame constitucional e capacidade prisional; reconhecimento facial precisa de controle de erros, transparência e proteção de direitos.','Mais prisões podem elevar custos sem reduzir o comando das facções. Comparar esclarecimento, reincidência e investigação financeira.']
  }],
  ['hertz_dias','Hertz Dias','PSTU',16,'hertz-dias-propostas-de-governo','proposta-pstu',{
    economia: ['Jornada de 36 horas, fim da escala 6x1, aumento de 100% do salário mínimo e suspensão e auditoria da dívida.','6–8, 26–28','Aumento da renda e redução da jornada procuram redistribuir recursos e trabalho; revisão da dívida pretende mudar prioridades orçamentárias.','Conferir impactos nos preços, nas contratações e no financiamento público, incluindo obrigações vinculadas ao mínimo e efeitos sobre credores.','A renda real depende dos preços e do emprego; aumentos nominais não garantem o mesmo ganho de poder de compra.'],
    saude: ['SUS integralmente estatal, fim de organizações sociais, expansão dos CAPS e produção pública de medicamentos.','11, 26','Gestão e produção públicas procuram reduzir dependências e ampliar acesso ao tratamento, incluindo saúde mental.','Conferir capacidade produtiva, contratação de pessoal e transição dos serviços; acompanhar falta de medicamentos e continuidade do cuidado.','Produção pública pode reduzir vulnerabilidade ou enfrentar custos e atrasos. Comparar qualidade, preço e regularidade do fornecimento.'],
    educacao: ['Educação integralmente pública, fim de parcerias e terceirizações, revisão curricular e permanência estudantil.','11–12','Financiamento público e apoio à permanência procuram ampliar acesso e reduzir o abandono.','Conferir expansão das vagas e transição dos contratos; mudanças curriculares precisam de materiais, formação e avaliação de aprendizagem.','Mais gestão pública não demonstra, sozinha, melhor ensino. Compare cobertura, recursos e desempenho dos alunos ao longo do tempo.'],
    seguranca: ['Polícia civil unificada, desmilitarização, descriminalização das drogas, câmeras corporais e investigação patrimonial.','19','Controle externo e integração procuram reduzir violência institucional; investigação patrimonial busca limitar o financiamento criminal.','Medir letalidade, investigação e violência após a reforma; mudanças na política de drogas precisam de regulação, prevenção e capacidade de cuidado.','Reorganização policial e câmeras podem ter efeitos distintos; avaliar cada componente e a qualidade de sua implantação.']
  }],
  ['leonardo_avalanche','Leonardo Avalanche','PRTB',28,'leonardo-avalanche','proposta-prtb',{
    economia: ['Imposto único de 3,5%, desoneração industrial e apoio ao primeiro emprego com complemento salarial público.','4–6, 21–22, 42','Simplificação busca reduzir burocracia; apoio salarial pretende diminuir o custo inicial da contratação.','Conferir base do imposto, arrecadação substituída e distribuição da carga; subsídio precisa demonstrar empregos adicionais, não só contratações que já ocorreriam.','Menos obrigações pode ajudar empresas, mas a forma de tributar pode acumular custos na cadeia. Comparar preços e arrecadação.'],
    saude: ['Mutirões e parcerias privadas para eliminar filas, controle de estoques com IA e rede de saúde mental para jovens.','9–10, 43','Oferta adicional e melhor controle de estoques procuram reduzir espera e falta de insumos.','Zerar uma fila exige considerar novas entradas. Conferir custo recorrente, especialistas, qualidade e critérios clínicos, inclusive dos serviços digitais.','Mutirões podem reduzir um estoque temporário sem resolver o fluxo permanente. Avaliar continuidade após o programa inicial.'],
    educacao: ['Ensino tecnológico e financeiro, inglês, inteligência emocional e qualificação digital com equipamentos e conectividade.','7, 15–16, 44','Tecnologia e formação procuram ampliar acesso a ferramentas e habilidades úteis ao estudo e ao trabalho.','Distribuir aparelhos não demonstra aprendizado. Conferir manutenção, uso pedagógico, formação docente e resultados para alunos sem conectividade em casa.','Material e apoio docente podem produzir ganhos sem equipamentos novos; comparar intervenções e custos antes de atribuir o resultado à tecnologia.'],
    seguranca: ['Bases policiais integradas, reconhecimento facial, penas mais duras e isolamento de líderes de facções.','13–14','Integração procura melhorar identificação e investigação; isolamento pretende restringir comando criminal a partir das prisões.','Conferir erros de identificação, proteção de dados, controle judicial e capacidade prisional; medir violência, não somente detenções.','Monitoramento pode deslocar crimes entre áreas. Comparar resultados nos territórios próximos e manter investigação financeira e prevenção.']
  }],
  ['lula','Lula','PT',13,'lula-propostas-de-governo','proposta-pt',{
    economia: ['Responsabilidade fiscal, Nova Indústria Brasil, renegociação de dívidas, valorização do mínimo e redução da jornada.','6–14, 47–58, 73–77','Renda e renegociação procuram apoiar consumo; política industrial procura ampliar capacidade produtiva e investimento.','Conferir custo dos incentivos e seu retorno, despesas vinculadas ao mínimo e trajetória fiscal; produção e emprego precisam de avaliação independente.','Crédito e renda podem estimular atividade ou elevar preços e dívida. Comparar ganhos duradouros de produtividade e distribuição dos benefícios.'],
    saude: ['Ampliar o Agora Tem Especialistas, Mais Médicos, acesso a medicamentos e atenção à saúde mental.','34–40','Expansão da oferta e organização dos encaminhamentos procuram conectar atenção básica a exames, consultas e tratamentos especializados.','Números de procedimentos apresentados pelo plano são declarações do candidato. Conferir séries administrativas, tempo de espera e demanda ainda não atendida.','Mais procedimentos podem refletir maior acesso ou maior necessidade. O resultado para o paciente precisa ser medido além da produção registrada.'],
    educacao: ['Alfabetização, formação docente, tempo integral, ensino técnico e permanência com o Pé-de-Meia.','30–34','Apoio financeiro procura reduzir abandono; formação e expansão da oferta procuram melhorar aprendizagem e conclusão.','Separar permanência de aprendizagem e conferir custo continuado. Comparar beneficiários e grupos semelhantes, considerando diferenças anteriores ao programa.','Um aluno pode permanecer e aprender pouco; combinar indicadores de frequência, conclusão e desempenho evita confundir objetivos.'],
    seguranca: ['Integração pelo SUSP, investigação financeira de facções, controle de armas e Ministério da Segurança Pública.','26–30','Coordenação de inteligência e controle de fluxos financeiros procuram dificultar recursos e articulação das organizações criminosas.','Conferir capacidade de investigação, integração com os estados e efeito das medidas; queda nacional não prova melhora em cada território.','Violência varia por estado e por tipo de crime. Comparar trajetórias locais e efeitos de políticas estaduais e federais.']
  }],
  ['renan_santos','Renan Santos','MISSÃO',14,'renan-santos-propostas-de-governo','proposta-missao',{
    economia: ['Desindexação de benefícios, desvinculação de pisos de saúde e educação e revisão de benefícios tributários e do abono salarial.','9–10','Alterar vinculações e revisar benefícios procura reduzir o crescimento automático de despesas e ampliar a margem de escolha do orçamento.','A economia de R$ 1,1 trilhão até 2031 é projeção do plano, não cálculo validado aqui. Conferir hipóteses e distribuição das perdas.','Maior flexibilidade pode melhorar alocação ou reduzir proteção aos serviços; comparar orçamento executado, acesso e efeito por renda.'],
    saude: ['Organização nacional de riscos e filas, prontuário integrado e financiamento associado a metas assistenciais.','25–26','Informação compartilhada e coordenação regional procuram direcionar pacientes e recursos conforme necessidade e capacidade.','Conferir privacidade, implantação, qualidade dos dados e desenho das metas; incentivos não devem premiar exclusão de casos complexos.','Uma fila digital pode organizar uma oferta insuficiente sem ampliá-la. Comparar necessidade regional, especialistas disponíveis e espera real.'],
    educacao: ['Alfabetização fônica, escolas cívico-militares, disciplina e avaliação por resultados e foco técnico-científico.','30–32','Mudanças pedagógicas e de gestão procuram melhorar aprendizagem e direcionar formação a áreas consideradas prioritárias.','Comparar escolas com recursos e perfis equivalentes. Rankings sem contexto podem premiar seleção de alunos em vez de avanço de aprendizagem.','Resultados melhores podem decorrer de seleção, financiamento ou perfil familiar; avaliar quanto cada estudante avançou.'],
    seguranca: ['Modelo prisional inspirado no CECOT, tratamento penal diferenciado para facções e medidas patrimoniais.','11–13','Isolamento e restrições penais e patrimoniais procuram reduzir a capacidade operacional do crime organizado.','Transferir um modelo estrangeiro exige examinar contexto, garantias constitucionais, custos e evidência; conferência jurídica específica ainda não concluída.','Menos crimes após uma medida não prova causalidade. Compare mudanças no registro, deslocamento do crime e outras políticas simultâneas.']
  }],
  ['caiado','Ronaldo Caiado','PSD',55,'ronaldo-caiado-propostas-de-governo','proposta-psd',{
    economia: ['Orçamento da Verdade, estratégia fiscal plurianual, controle de despesas obrigatórias, revisão de subsídios e agenda de produtividade.','12–15','Diagnóstico fiscal e revisão de gastos procuram orientar prioridades e estabilizar dívida; produtividade busca sustentar crescimento.','Conferir medidas e transição das despesas, hipóteses de receita e juros e proteção do investimento; diagnóstico não equivale a ajuste executado.','Reduzir despesas pode melhorar sustentabilidade ou limitar serviços. Comparar composição do ajuste e efeito sobre produção e acesso.'],
    saude: ['Fila transparente, regulação inteligente, atenção primária, rede contra o câncer e saúde mental.','77–80, 84','Transparência e coordenação procuram ordenar acesso; atenção primária e redes especializadas procuram tratar necessidades diferentes.','Conferir oferta regional, profissionais e custeio; publicar filas precisa incluir quem aguarda fora das listas formais.','Organizar listas revela demanda reprimida e pode elevar a fila publicada inicialmente. Avaliar espera e tratamento concluído, não só tamanho da lista.'],
    educacao: ['Alfabetização e recuperação da aprendizagem, creches, tempo integral e formação e liderança docente.','32–33','A proposta combina intervenção precoce e apoio à escola para reduzir defasagens e ampliar oportunidades de aprendizagem.','Conferir vagas, formação, infraestrutura e jornada docente; comparar aprendizagem por etapa e vulnerabilidade.','Expansão de horas pode ajudar quando há ensino adequado; sem equipe e estrutura, mais tempo não garante avanço.'],
    seguranca: ['Ministério da Segurança, inteligência nacional, asfixia financeira de facções e controle penitenciário.','16–20','Coordenação e investigação patrimonial procuram integrar operações e reduzir recursos e comando criminal.','Conferir orçamento, competências federais e estaduais e controles; mudanças penais precisam de análise constitucional e avaliação de resultados.','Uma nova estrutura pode melhorar coordenação ou duplicar atribuições. Medir investigação, violência e custo, além do número de operações.']
  }],
  ['rui_costa_pimenta','Rui Costa Pimenta','PCO',29,'rui-costa-pimenta-propostas-de-governo','pcoprogramadegoverno2026-1',{
    economia: ['Aumento emergencial de 50% dos salários, jornada de 35 horas, cancelamento de dívidas e estatização financeira.','2–3, 6','Elevar renda e reorganizar o crédito busca redistribuir recursos e ampliar consumo e proteção dos trabalhadores.','Conferir efeitos sobre preços, emprego, contratos, credores e financiamento; diferenciar promessa nominal de ganho real e de capacidade produtiva.','Distribuir renda pode elevar consumo, mas oferta e produtividade condicionam o resultado; aumentos de preços podem reduzir o ganho real.'],
    saude: ['Construção emergencial de hospitais e postos, expansão da formação de médicos e enfermagem e aumento de recursos.','4–5','Expansão física e de profissionais procura ampliar a capacidade de atendimento e reduzir carências regionais.','Conferir tempo de formação, qualidade, equipes e despesas permanentes. Abrir cursos ou hospitais não produz atendimento completo imediatamente.','Redistribuir profissionais e melhorar regulação pode reduzir carências antes da conclusão de novas unidades; comparar prazos e custos.'],
    educacao: ['Estatização do ensino privado, livre ingresso universitário, gestão eleita e valorização dos professores.','4–5','Expansão do acesso público e mudanças de gestão procuram ampliar participação e reduzir barreiras financeiras.','Dimensionar vagas, custeio, qualidade e transição patrimonial; acesso sem apoio à permanência não garante conclusão.','A universalização pode exigir expansão gradual de capacidade. Comparar alternativas que preservem atendimento e aprendizagem durante a transição.'],
    seguranca: ['Dissolução da Polícia Militar e do aparato repressivo e comitês de autodefesa dos trabalhadores.','5–6','A proposta pretende substituir a organização atual da segurança por estruturas de autodefesa.','Conferir desenho de transição, autoridade legal, fiscalização e proteção de toda a população; compatibilidade constitucional não foi validada nesta revisão.','Uma mudança estrutural deve ser comparada também com reformas de treinamento, investigação e controle externo no sistema existente.']
  }],
  ['samara','Samara','UP',80,'samara-propostas-de-governo','proposta-up',{
    economia: ['Aumento de 100% do mínimo, redução da jornada, frentes públicas de trabalho, tributação progressiva e suspensão e auditoria da dívida.','7–18','Emprego público e renda buscam ampliar proteção; mudanças tributárias e da dívida procuram redirecionar recursos.','Conferir custo continuado, produtividade das frentes e efeitos da suspensão sobre financiamento e contratos; receitas projetadas precisam de hipóteses explícitas.','Empregos criados podem ser temporários ou permanentes. Comparar renda, formalização e inserção posterior, além do número de vagas anunciado.'],
    saude: ['Gestão integralmente estatal, fim das organizações sociais, produção nacional de medicamentos e valorização dos trabalhadores.','19–20','Reorganização da gestão e produção nacional procuram aumentar capacidade pública e reduzir dependência de insumos externos.','Conferir transição de contratos, aquisição de insumos, pessoal e custeio; medir continuidade do atendimento e falta de medicamentos.','Produção nacional pode ampliar segurança de abastecimento, mas exige capacidade e qualidade; comparar custo, prazo e regularidade.'],
    educacao: ['Livre acesso técnico e superior, revisão do FIES, estatização de conglomerados e pelo menos 10% do PIB para educação pública.','21–23','Acesso e financiamento público procuram ampliar oportunidades e reduzir o custo direto para estudantes.','Percentual do PIB é meta de gasto, não garantia de receita. Conferir expansão de vagas, qualidade e distribuição entre etapas de ensino.','Gasto agregado maior pode deixar desigualdades locais intactas. Comparar recursos por aluno, aprendizagem e atendimento das regiões mais vulneráveis.'],
    seguranca: ['Desmilitarização e unificação policial, assembleias populares de segurança, mudança da política de drogas e reeducação prisional.','48–50','Participação social e reorganização policial procuram alterar controle e prevenção; reinserção procura reduzir reincidência.','Conferir responsabilidades, transição e controle externo; avaliar proteção, investigação e qualidade dos serviços sem presumir resultado pelo modelo institucional.','Participação pode melhorar diagnóstico ou ter representação desigual; medir acesso, capacidade de resposta e proteção de grupos vulneráveis.']
  }],
  ['wilson_grassi','Veterinário Wilson Grassi','DEMOCRATA',35,'wilson-grassi','proposta-democrata',{
    economia: ['Imposto Único Federal sobre movimentação financeira, desoneração da folha e ambiente digital único para empresas.','8–10, 13–20','Simplificação e menor custo direto da contratação procuram reduzir burocracia e estimular formalização.','Conferir arrecadação substituída, efeito em cadeias produtivas e financiamento da proteção social; abertura de CNPJ não equivale a emprego novo.','Um tributo simples de cobrar pode aumentar custo em transações sucessivas. Comparar preços, distribuição e estabilidade da arrecadação.'],
    saude: ['Prioridade à atenção primária, fila pública única, prontuário integrado e Saúde Única humana, animal e ambiental.','26–28, 34–35','Integração de cuidados e vigilância procura antecipar riscos e organizar acesso entre serviços.','Conferir interoperabilidade, equipes, cobertura e custeio; uma lista única precisa refletir prioridades clínicas e barreiras regionais.','Integrar dados pode revelar problemas antes invisíveis sem reduzir espera de imediato. Comparar detecção, encaminhamento e tratamento concluído.'],
    educacao: ['Alfabetização na idade certa, formação técnica, educação física e mudança da situação dos bolsistas de pesquisa.','36, 38','A proposta combina formação básica, preparação profissional e apoio à pesquisa e à atividade física escolar.','Separar os objetivos e os orçamentos; formação técnica precisa de demanda regional e alfabetização de acompanhamento pedagógico.','Metas administrativas podem expandir a oferta sem melhorar resultados. Comparar aprendizagem, conclusão e inserção profissional.'],
    seguranca: ['Investigação patrimonial das facções, controle de fronteiras e isolamento do comando em presídios de segurança máxima.','21–23, 50','Restrição a recursos e comunicação procura reduzir a capacidade de operação e coordenação do crime organizado.','Conferir integração investigativa e capacidade prisional; fiscalização deve medir resultados e observar garantias legais e controle judicial.','Isolamento pode limitar comandos ou deslocá-los. Comparar continuidade das redes, violência e eficácia das investigações financeiras.']
  }],
  ['zema','Zema','NOVO',30,'zema','proposta-novo',{
    economia: ['Ajuste fiscal, privatização de estatais, reformas administrativa e previdenciária e redução de impostos.','14–19','Reformas procuram reduzir despesa recorrente; privatizações alteram a atuação estatal e podem gerar receitas de venda.','Separar venda de ativos de economia permanente e perda de receitas futuras; conferir concorrência, regulação e efeito de reduzir tributos.','Menor presença estatal pode elevar eficiência ou gerar concentração. Comparar qualidade, preço e obrigações de serviço em cada setor.'],
    saude: ['Telessaúde, registros integrados e parcerias para usar capacidade privada disponível e ampliar a rede.','57–60','Contratar capacidade e integrar registros procura aumentar atendimento e diminuir gargalos da rede.','Conferir preços, fiscalização, profissionais e distribuição regional; uma parceria envolve pagamentos e obrigações, mesmo com gestão privada.','Onde não há capacidade privada disponível, o gargalo permanece. Comparar construção pública, contratos e fortalecimento da atenção básica.'],
    educacao: ['Parcerias para creches, revisão da BNCC, alfabetização, formação docente e bolsas ligadas à presença e aprendizagem.','50–54','Expansão da oferta e incentivos procuram ampliar acesso e aprendizagem e alinhar apoio financeiro a resultados.','Conferir critérios das bolsas e proteção de estudantes vulneráveis; desempenho baixo pode refletir necessidade de apoio, não falta de esforço.','Condicionar benefícios pode incentivar participação ou excluir quem tem mais dificuldade. Comparar abandono e aprendizagem entre grupos equivalentes.'],
    seguranca: ['Facções tratadas como terrorismo, presídios remotos de segurança máxima e redução da maioridade penal.','5–7','Mudanças penais e isolamento procuram elevar restrições e reduzir o comando e a operação de organizações criminosas.','Conferir compatibilidade constitucional, custos e capacidade prisional; endurecimento da lei não demonstra, sozinho, redução de violência.','Investigação e prevenção podem explicar parte da queda dos crimes. Comparar esclarecimento e reincidência, além do tamanho das penas.']
  }]
];

export const CANDIDATES = records.map(([id, name, party, number, slug, pdf, proposals]) => ({
  id, name, party, number, indexUrl: BASE + slug,
  planUrl: 'https://www.tse.jus.br/eleicoes/eleicoes-2026-content/arquivos/' + pdf,
  sourceBasis: 'Síntese do índice temático do TSE; as páginas são as indicadas pelo índice.',
  topics: Object.fromEntries(Object.entries(proposals).map(([key, [summary, pages, mechanism, limits, alternative]]) => [key, {
    summary, pages, mechanism, limits, alternative,
    costStatus: 'não auditado', legalStatus: 'não auditado',
    conclusion: 'A fonte documenta a proposta. Este recorte permite comparar o caminho escolhido; não demonstra eficácia, custo total nem execução garantida.'
  }]))
}));

// Passagens econômicas adicionais lidas diretamente nos PDFs, além do índice.
export const DOCUMENT_NOTES = {
  lula: {topic:'saude', pages:'37', text:'O PDF prevê ampliar turnos, mutirões e parcerias privadas por créditos financeiros ou dívidas. É um mecanismo descrito no plano; os resultados que o texto atribui ao programa não foram checados como fatos nesta revisão.'},
  flavio_bolsonaro: {topic:'economia', pages:'71', text:'O PDF propõe superávits primários, limite ao crédito subsidiado do Tesouro e controle de gastos discricionários. O trecho descreve instrumentos; não fornece aqui uma demonstração independente do impacto projetado.'},
  zema: {topic:'economia', pages:'15–16', text:'O PDF propõe privatizar estatais, vender imóveis públicos e fixar metas de redução tributária. Receita de venda é diferente de economia recorrente; essa diferença precisa entrar na avaliação fiscal.'},
  caiado: {topic:'economia', pages:'12–13', text:'O PDF prevê diagnóstico fiscal nos primeiros meses, metas anuais e transição do controle das despesas obrigatórias. É um roteiro declarado; o cumprimento e os efeitos ainda precisam ser avaliados.'},
  renan_santos: {topic:'economia', pages:'10', text:'O PDF estima economia de R$ 1,1 trilhão até 2031 para a PEC do Equilíbrio Fiscal. A estimativa é do plano. Não foi reproduzida nem validada pelo projeto; parte do horizonte ultrapassa o mandato 2027–2030.'}
};
