export const POLL_REVIEW_DATE='02/10/2026';
// Uma observação nacional por instituto, com campo encerrado nos últimos 10 dias.
// null = sem dado individual publicado; {lt:1} = citado, mas abaixo de 1%.
const ids=['lula','flavio_bolsonaro','zema','caiado','renan_santos','augusto_cury','samara','edmilson_costa','wilson_grassi','clariana_barao','rui_costa_pimenta','leonardo_avalanche','hertz_dias'];
const map=values=>Object.fromEntries(ids.map((id,i)=>[id,values[i]]));
export const POLLS=[
 {id:'datafolha-20261001',institute:'Datafolha',published:'02/10/2026',field:'29/09–01/10/2026',fieldEnd:'2026-10-01',sample:2506,margin:2,confidence:95,registration:'BR-08039/2026',population:'Eleitores de 16 anos ou mais',method:'Entrevistas presenciais em 152 municípios',source:'https://datafolha.folha.uol.com.br/eleicoes/2026/10/no-1o-turno-lula-pt-lidera-com-45-dos-validos-e-flavio-bolsonaro-pl-tem-40.shtml',voteReference:'Total de votos · 1º turno estimulado; não são votos válidos',rejectionQuestion:'Candidatos em quem não votaria de jeito nenhum',votes:map([42,38,1,3,3,4,1,{lt:1},{lt:1},{lt:1},{lt:1},{lt:1},{lt:1}]),rejection:map([45,45,15,14,16,11,9,9,null,null,11,null,null])},
 {id:'quaest-20260928',institute:'Quaest',published:'28/09/2026',field:'24–27/09/2026',fieldEnd:'2026-09-27',sample:2004,margin:2,confidence:95,registration:'BR-06520/2026',population:'Eleitores de 16 anos ou mais',method:'Entrevistas pessoais domiciliares',source:'https://static.poder360.com.br/uploads/2026/09/pesquisa-quaest-presidente-28set2026v2.pdf',institutePage:'https://quaest.com.br/relatorios/pesquisa-de-intencao-de-voto-para-presidente-rodada-6-28-09-2026/',voteReference:'PDF p. 18 · 1º turno estimulado, cenário 1 · última coluna (28/Set)',rejectionReference:'PDF p. 83 e 85 · última coluna (28/Set)',rejectionQuestion:'Conhece e não votaria de jeito nenhum, após distinguir desconhecimento e possibilidade de voto',votes:map([39,34,1,4,3,4,0,0,0,0,0,0,0]),rejection:map([54,56,45,40,35,31,14,13,12,10,23,12,13]),unknown:map([0,1,35,32,50,45,83,85,86,89,74,87,86])},
 {id:'atlas-20260929',institute:'AtlasIntel/Bloomberg',published:'29/09/2026',field:'23–28/09/2026',fieldEnd:'2026-09-28',sample:5005,margin:1,confidence:95,registration:'BR-04391/2026',population:'População adulta brasileira',method:'Recrutamento digital aleatório (Atlas RDR), com pós-estratificação',source:'https://cdn1.atlasintel.org/pesquisa_atlas_bloomberg__nacional_260929_f6e4ce397d269a6f.pdf',institutePage:'https://atlasintel.org/poll/brazil-national-2026-09-29',voteReference:'PDF p. 14 · total de votos no 1º turno; metodologia p. 5',rejectionQuestion:null,votes:map([45.3,42.2,.9,1.8,5.2,2,.4,0,0,0,.1,null,0]),rejection:map(ids.map(()=>null)),note:'Este relatório não publica rejeição. Leonardo Avalanche não aparece individualmente no gráfico; não foi convertido em zero.'}
];
export function voteAverage(id){const values=POLLS.map(p=>p.votes[id]).filter(v=>v!==null&&v!==undefined);if(!values.length)return {value:null,count:0,reason:'Sem dados'};if(values.some(v=>typeof v!=='number'))return {value:null,count:values.length,reason:'Sem média pontual: há resultado <1%'};return {value:values.reduce((a,b)=>a+b,0)/values.length,count:values.length,reason:null};}
export function percent(value){if(value===null||value===undefined)return 'Não publicado';if(typeof value==='object')return `<${value.lt}%`;return value.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';}
export const POLL_METHOD='Média aritmética simples, sem pesos, do total de intenção de voto nacional estimulada no 1º turno: uma rodada por instituto entre os relatórios Datafolha, Quaest e AtlasIntel/Bloomberg conferidos até 02/10/2026, com campo encerrado nos últimos 10 dias. Não mistura voto espontâneo, votos válidos, segundo turno ou pesquisas estaduais. Não é projeção eleitoral nem levantamento exaustivo de todos os institutos. Modos de entrevista, população-alvo e datas diferem. Não possui margem de erro combinada e não corrige efeito de instituto. Resultados censurados (<1%) não viram zero e impedem média pontual. Zero publicado permanece zero no cálculo, sujeito ao arredondamento da fonte. Rejeição permanece por instituto: questionários diferentes e ausência de dados não são combinados.';
