import { EVIDENCE as e } from './comparison-estimates.js?v=20261002_evidence1';
export const EXTRA_SOURCES = {
  evidence: ['Projeto · dados, fontes e cálculos auditáveis', 'dados/comparacoes-evidencias-2026-10-02.json'],
  incomeHistory: ['Projeto · renda histórica, IPCA e método', 'dados/renda-historico-2026-10-02.json'],
  wbTotal: ['Banco Mundial · crescimento real do PIB', 'https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG'],
  wbPer: ['Banco Mundial · crescimento real do PIB por habitante', 'https://data.worldbank.org/indicator/NY.GDP.PCAP.KD.ZG'],
  pisaTables: ['OCDE · PISA 2025 · tabelas I.B1.2a.36–38', 'https://stat.link/mrq53f'],
  laborSeries: ['IBGE · SIDRA 4099 · desocupação e subutilização', 'https://sidra.ibge.gov.br/tabela/4099'],
  participation: ['IBGE · SIDRA 6461 · participação', 'https://sidra.ibge.gov.br/tabela/6461'],
  rtnDetail: ['Tesouro · RTN agosto/2026 · composição', 'https://www.tesourotransparente.gov.br/publicacoes/boletim-resultado-do-tesouro-nacional-rtn/2026/8'],
  rag: ['Ministério da Saúde · RAG 2025 · quadros 5 e 30', 'https://bvsms.saude.gov.br/bvs/publicacoes/relatorio_anual_gestao_2025.pdf'],
  rqpc: ['Ministério da Saúde · 1º RQPC 2026 · quadro 4', 'https://bvsms.saude.gov.br/bvs/publicacoes/1_rqpc_2026.pdf'],
  globalHunger: ['FAO · SOFI 2026 · resultados mundiais', 'https://www.fao.org/newsroom/detail/un-report--global-hunger-levels-ease-for-third-consecutive-year-as-regional-disparities-persist/']
};
const n=v=>v.toLocaleString('pt-BR',{maximumFractionDigits:2});
const text=(title,paragraphs,sources,status)=>({title,paragraphs,sources,status});
const table=(caption,headers,rows,note,sources)=>({caption,headers,rows,note,sources});
const line=(id,caption,labels,chartRows,chartMax,unit,note,sources)=>({...table(caption,['Ano',...labels],chartRows.map(r=>r.map((v,i)=>i?n(v):String(v))),note,sources),id,layout:'year',presentation:'lines',labels,chartRows,chartMax,unit});
const topic=(id,title,question,purpose,tables,explanation,alternative,conclusion,nextEvidence,sources)=>({id,title,navLabel:title,stats:[],reading:[],cycle:{question,purpose,tables,explanation,alternative,conclusion,nextEvidence,sources,detailLabel:'Abrir conceitos e metodologia'}});
const growth=(a,b)=>(b/a-1)*100;
const series=(rows,variable)=>rows.filter(r=>r.D2C===variable).sort((a,b)=>a.D3C.localeCompare(b.D3C)).map(r=>[Number(r.D3C.slice(0,4)),Number(r.V)]);
const wbIndex=(kind,codes)=>{
  const obs=e.worldbank[kind].observations;
  const indices=codes.map(code=>{let v=100;return [100,...[2023,2024,2025].map(year=>{const row=obs.find(r=>(r.countryiso3code===code||(code==='UMC'&&r.country.id==='XT'))&&r.date===String(year));if(!row||row.value===null)throw Error('Observação WDI ausente');v*=1+row.value/100;return v;})];});
  return [2022,2023,2024,2025].map((year,i)=>[year,...indices.map(s=>s[i])]);
};
export function extendEvidence(areas){
  const economy=areas.find(a=>a.id==='scene-panorama');
  const find=id=>areas.flatMap(a=>a.blocks).find(b=>b.id===id).cycle;
  const income=find('economia-bolso');
  income.tables.push(line('renda-historica','Renda do trabalho · 2º trimestre · preços do 2º trimestre/2026',['Média','Mediana'],e.income.rows.map(r=>[r.year,r.real_mean,r.real_percentiles['50']]),4500,'R$ por mês', 'Estimativas do projeto: IPCA nacional médio de abril–junho, sem os deflatores regionais oficiais da PNAD. Anos selecionados; não há observações de 2023–2024 neste gráfico. Ocupados 14+ com renda habitual positiva, pesos V1028; sem intervalos de confiança.', ['incomeHistory']));
  income.tables.push(table('O ganho chega a diferentes posições da distribuição?', ['Posição','2022 → 2026','2025 → 2026'],['10','50','90'].map(p=>['P'+p+(p==='50'?' · mediana':''),n(growth(e.income.rows[0].real_percentiles[p],e.income.rows[2].real_percentiles[p]))+'%',n(growth(e.income.rows[1].real_percentiles[p],e.income.rows[2].real_percentiles[p]))+'%']), 'Mesmo trimestre, população e correção de preços. P10 é o limite abaixo do qual estão 10% dos rendimentos ponderados; P90, 90%. Não são a renda média desses grupos nem o ganho dos mesmos indivíduos.', ['incomeHistory']));
  income.alternative=text('A melhora recente foi uniforme?', ['Hipótese de ganho igual para todos: contrariada pelos pontos estimados. Entre 2025 e 2026, a mediana real estimada aumentou cerca de 10%, mas o P90 caiu aproximadamente 4,4%. Na comparação mais longa, de 2022 a 2026, os três percentis apresentados aumentaram.', 'Isso descreve posições de distribuições distintas, não trajetórias individuais. Composição dos ocupados, revisões de pesos e incerteza amostral importam. Não calculamos intervalos de confiança para esses quantis; pequenas diferenças exigem cautela.'],['incomeHistory'],'Contrariada: ganho uniforme nos percentis apresentados');
  income.conclusion='A mediana real estimada passou de cerca de R$ 1.902 em 2022 para R$ 2.300 em 2026, no mesmo trimestre e na correção pelo IPCA adotada pelo projeto. Há melhora no centro da distribuição, com trajetórias diferentes entre percentis. Não equivale a aumento de renda para cada trabalhador.';
  income.nextEvidence='Intervalos de confiança dos quantis, deflatores regionais oficiais, distribuição por território e renda domiciliar por pessoa. A comparação histórica já está disponível; esses recortes ainda não foram estimados.';

  const work=find('economia-trabalho');
  const un=series(e.labor,'4099'),sub=series(e.labor,'4118'),part=series(e.participation,'4096');
  work.tables.push(line('trabalho-historico','Mercado de trabalho · Brasil · 2º trimestre de cada ano',['Desocupação','Subutilização'],un.map((r,i)=>[r[0],r[1],sub[i][1]]),30,'%', 'Desocupação: desocupados / força de trabalho. Subutilização: inclui subocupação por horas e força potencial, sobre a força ampliada. Denominadores diferentes; não somar nem subtrair as taxas.', ['laborSeries']));
  work.tables.push(line('participacao-historica','Participação na força de trabalho · Brasil · 2º trimestre',['Participação'],part,100,'% das pessoas de 14 anos ou mais', 'Participação mede ocupados + desocupados em relação à população de 14+. Quem não busca não é automaticamente desalentado: estudos, aposentadoria, cuidados e outros motivos também importam.', ['participation']));
  work.explanation.paragraphs.push('Na série do mesmo trimestre, a desocupação e a subutilização caem. A participação, porém, passa de 62,4% em 2025 para 62,1% em 2026. Portanto, há mais de um movimento para explicar: melhorar a taxa de desemprego não encerra a avaliação do mercado de trabalho.');
  work.explanation.sources.push('laborSeries','participation');
  work.alternative.status='Não demonstrada: queda explicada apenas por desistência';
  work.alternative.paragraphs.push('A queda conjunta da desocupação e da subutilização enfraquece a explicação de que tudo seja apenas saída da busca. A redução da participação no último intervalo, por outro lado, exige olhar os motivos de saída e o nível de ocupação. Uma série agregada não identifica esses motivos nem o efeito causal de benefícios sociais.');
  work.alternative.sources.push('laborSeries','participation');
  work.conclusion+=' A leitura histórica confirma queda da subutilização, mas a participação recente também diminuiu: os dois fatos precisam aparecer juntos.';
  const groups=[['Norte',['Acre','Amapá','Amazonas','Pará','Rondônia','Roraima','Tocantins']],['Nordeste',['Alagoas','Bahia','Ceará','Maranhão','Paraíba','Pernambuco','Piauí','Rio Grande do Norte','Sergipe']],['Centro-Oeste',['Distrito Federal','Goiás','Mato Grosso','Mato Grosso do Sul']],['Sudeste',['Espírito Santo','Minas Gerais','Rio de Janeiro','São Paulo']],['Sul',['Paraná','Rio Grande do Sul','Santa Catarina']]];
  work.tables.push(table('A média nacional representa cada estado? · desocupação no 2º trimestre/2026',['Região','Menor taxa · UF','Maior taxa · UF'],groups.map(([region,names])=>{const rs=e.labor_states.filter(r=>r.D3C==='202602'&&names.includes(r.D1N)).sort((a,b)=>Number(a.V)-Number(b.V));if(rs.length!==names.length)throw Error('UF ausente');return [region,n(Number(rs[0].V))+'% · '+rs[0].D1N,n(Number(rs.at(-1).V))+'% · '+rs.at(-1).D1N];}), 'Extremos entre estados em cada região, não taxas regionais nem ranking ajustado por perfil. Todos os 27 estados/DF e os dois trimestres estão no JSON público. Comparações pontuais sem teste de significância.', ['laborSeries','evidence']));

  const world=wbIndex('percapita',['BRA','WLD','LCN']);
  const peers=wbIndex('percapita',['BRA','MIC','UMC']);
  const totals=wbIndex('total',['BRA','WLD','LCN']);
  economy.blocks.splice(economy.blocks.findIndex(b=>b.id==='economia-contas'),0,topic('economia-mundo','Brasil e mundo','O Brasil melhorou ou apenas mudou de posição?', 'Confronte crescimento interno com referências externas explícitas. Crescer e superar a referência são perguntas diferentes.',[
    line('pib-mundo','PIB real · trajetória desde 2022',['Brasil','Mundo','América Latina e Caribe'],totals,120,'Índice · 2022 = 100','Índices calculados pelo projeto, encadeando as variações reais de 2023, 2024 e 2025. Não somar taxas. A referência regional inclui todos os níveis de renda; o mundo inclui o Brasil. Dados WDI revisáveis, consulta em 02/10/2026; 2026 excluído.', ['wbTotal','evidence']),
    line('pib-pessoa-mundo','PIB real por habitante · mesmas referências',['Brasil','Mundo','América Latina e Caribe'],world,120,'Índice · 2022 = 100','Mesma fonte e intervalo. Uma base igual permite comparar crescimento, não níveis de riqueza. PIB por habitante não é salário nem renda mediana; não mostra como o produto é distribuído.', ['wbPer','evidence']),
    line('pib-pares','PIB real por habitante · comparação por renda',['Brasil','Renda média','Renda média alta'],peers,120,'Índice · 2022 = 100','Agregados WDI MIC e UMC, não média simples de países. Grupos sobrepostos e distintos de mundo/América Latina; não são um contrafactual causal do Brasil. A composição da classificação pode mudar; o JSON preserva a consulta.', ['wbPer','evidence'])
  ],text('Um avanço absoluto pode coexistir com atraso relativo',[`De 2022 a 2025, o PIB real por habitante cresceu ${n(world.at(-1)[1]-100)}% no Brasil, ${n(world.at(-1)[2]-100)}% no mundo e ${n(peers.at(-1)[2]-100)}% no agregado de renda média. Assim, o Brasil avançou internamente e superou o crescimento mundial neste intervalo, mas ficou abaixo do grupo de renda média.`, 'A escolha da referência muda a pergunta. O PIB total inclui crescimento populacional; o PIB por habitante retira esse componente. Rankings em dólares correntes também mudam com câmbio e preços, sem necessariamente representar avanço real.'],['wbPer','evidence']),text('Foi o resto do mundo que piorou?', ['Neste recorte, os índices mundiais de PIB total e por habitante aumentam: a hipótese de queda do mundo é contrariada. Isso não significa melhora em todos os países ou em todos os indicadores.', 'Guerras, commodities, juros externos, safra e demanda podem influenciar a economia. Estes agregados não isolam seus efeitos nem demonstram que o crescimento ocorreu por mérito exclusivo do governo ou apesar dele. Escolher apenas países em crise também enviesaria a comparação.'],['wbTotal','wbPer'],'Contrariada neste indicador e intervalo'), 'O Brasil cresceu em termos reais. O desempenho relativo foi superior ao mundial e inferior ao dos agregados de renda média mostrados. Nenhuma dessas comparações, isoladamente, identifica a causa do crescimento.', 'Mesmas séries revisadas, pares definidos antes da comparação, produtividade, distribuição da renda e avaliações que controlem fatores externos.', ['wbTotal','wbPer','evidence']));

  const fiscal=find('economia-contas');
  fiscal.tables.push(table('Resultado primário do Governo Central · janeiro–agosto',['Medida','2025','2026'],[['Déficit nominal · R$ bilhões','85,9','94,9']], 'Mesmos oito meses. Resultado primário exclui juros; Governo Central difere do setor público consolidado. Não comparar diretamente com os fluxos de 12 meses das estatísticas do BCB.', ['rtnDetail']));
  fiscal.tables.push(table('Onde a despesa primária aumentou? · jan–ago/2026 contra jan–ago/2025',['Categoria','Aumento real · R$ bi','Variação real'],[['Benefícios previdenciários','29,34','3,9%'],['Pessoal e encargos','15,00','5,5%'],['Créditos extraordinários','10,60','283,5%'],['Despesas discricionárias','35,80','31,8%']], 'Categorias selecionadas do RTN, não decomposição exaustiva. Variação em preços constantes, não nível gasto, participação no total ou contribuição à dívida. Os exemplos de saúde/educação abaixo estão dentro das discricionárias: não somar novamente.', ['rtnDetail']));
  fiscal.tables.push(table('Como a arrecadação mudou? · jan–ago/2026 contra jan–ago/2025',['Receita selecionada','Mudança real · R$ bi','Variação real'],[['Arrecadação previdenciária','+29,12','+6,2%'],['Imposto de Renda','+19,60','+3,2%'],['IOF','+13,15','+24,1%'],['Cofins','+14,20','+5,4%'],['CSLL','+9,09','+6,8%'],['Dividendos','−15,80','−45,0%'],['Recursos naturais','+17,91','+18,9%']], 'Seleção de receitas brutas tributárias e não tributárias do RTN. Não soma a variação da receita líquida: outras rubricas e transferências a estados/municípios também entram. Crescimento da arrecadação pode refletir atividade, preços, mudanças legais e eventos extraordinários; não é a mesma medida que carga tributária/PIB.', ['rtnDetail']));
  fiscal.explanation.paragraphs.push('No acumulado de oito meses, receita líquida e despesa cresceram ambas 5,7% em termos reais. As bases são diferentes: a receita aumentou R$ 90,0 bilhões e a despesa R$ 96,3 bilhões. Igual crescimento percentual não garante equilíbrio. Os déficits da tabela são nominais; não subtrair diretamente deles as variações reais.', 'Nas despesas discricionárias, o RTN identifica aumentos reais de R$ 16,2 bilhões na Saúde e R$ 10,3 bilhões na Educação; nesta última, R$ 9,5 bilhões em aportes ao FIPEM. Previdência, pessoal, decisões judiciais e créditos extraordinários também entram na explicação.');
  fiscal.explanation.sources.push('rtnDetail');
  fiscal.alternative.paragraphs.push('Uma melhora num mês não garante melhora no ano: o déficit de agosto diminuiu, enquanto o acumulado janeiro–agosto aumentou. Na arrecadação, IOF, receitas previdenciárias, tributos sobre renda e receitas de recursos naturais têm trajetórias próprias. Não atribua todo aumento da dívida a um único programa social.', 'Se a dívida cresce persistentemente mais que a capacidade de financiá-la, o serviço da dívida pode pressionar o orçamento e encarecer crédito. O resultado depende também do crescimento, juros, receitas, perfil e prazo da dívida. Reduzir gastos não é a única variável: receitas, eficiência e crescimento também importam; os efeitos de cada ajuste precisam ser avaliados.');
  fiscal.alternative.sources.push('rtnDetail');
  fiscal.alternative.status='Em aberto: custo causal de um programa na dívida';

  const future=find('economia-futuro');
  future.tables.push(line('fome-mundo','Subalimentação no mundo · anos selecionados',['Mundo'],[[2022,8.6],[2024,8.1],[2025,7.8]],15,'% da população mundial','SOFI 2026. Estimativas anuais globais; não são os percentuais trienais brasileiros de insegurança alimentar. Não preencher 2023 nem equiparar subalimentação a insegurança moderada/grave.', ['globalHunger']));
  future.alternative.paragraphs.push('No mundo, a prevalência de subalimentação caiu de 8,6% em 2022 para 7,8% em 2025. Portanto, a hipótese geral de que o Brasil parece melhor apenas porque o mundo piorou não é sustentada por esse indicador. Há desigualdades regionais e conflitos, mas sua contribuição causal não é estimada aqui.');
  future.alternative.sources.push('globalHunger');
  future.alternative.status='Contrariada: piora global neste indicador';

  const edu=areas.find(a=>a.id==='scene-educacao');
  const m=e.pisa.matematica;
  edu.blocks.push(topic('educacao-internacional','Comparação internacional','Aproximar-se da OCDE significa aprender mais?', 'Separe a mudança da nota brasileira da mudança da referência externa. Compare o mesmo grupo de países ao longo do tempo.',[
    ...[['matematica','Matemática'],['leitura','Leitura'],['ciencias','Ciências']].map(([key,label])=>{const p=e.pisa[key];return line('pisa-'+key,'PISA · '+label,['Brasil','OCDE · grupo constante de 35'],p.years.map((year,i)=>[year,p.brazil[i],p.oecd35[i]]),600,'Pontos na escala PISA','Mesmas 35 economias da linha OECD average-35 nas tabelas oficiais, não média mundial ou conjunto variável de participantes. Estudantes elegíveis de 15 anos; não toda a população. Pontos não são porcentagem de conhecimento. Médias e erros-padrão no JSON público.', ['pisaTables','evidence']);})
  ],text('A distância diminui quando a referência cai mais',[`Em matemática, entre 2022 e 2025, o Brasil passa de ${n(m.brazil[2])} para ${n(m.brazil[3])} pontos; a referência constante passa de ${n(m.oecd35[2])} para ${n(m.oecd35[3])}. A distância cai de ${n(m.oecd35[2]-m.brazil[2])} para ${n(m.oecd35[3]-m.brazil[3])} pontos. Isso é aproximação relativa, sem aumento da média brasileira.`, 'A OCDE caracteriza os resultados brasileiros de 2025 como semelhantes aos de 2022 nas três áreas. Diferenças numéricas pequenas não são automaticamente mudanças estatisticamente demonstradas. A decomposição da distância aqui é descritiva; não calculamos significância da diferença entre as duas trajetórias.'],['pisa','pisaTables']),text('A queda externa explica tudo?', ['Para esta aproximação em matemática, a queda mais forte da referência externa sustenta a explicação relativa. Isso não apaga avanços brasileiros em outros períodos ou outros instrumentos, como o Saeb; cada série precisa ser examinada separadamente.', 'Não é possível atribuir a queda da OCDE a guerras com estes dados. Pandemia, composição, participação e mudanças educacionais são hipóteses a investigar. Ranking também depende de participantes e incerteza: não transformamos posições em medida de aprendizagem.'],['pisa','pisaTables'],'Sustentada: aproximação relativa em matemática'), 'Neste intervalo, uma distância menor para a referência não comprova avanço absoluto brasileiro. O PISA exige olhar as notas e a incerteza, junto com participação e desigualdade; posições isoladas podem induzir uma leitura errada.', 'Níveis de proficiência, participação, diferenças regionais e socioeconômicas, intervalos de confiança e comparações que mantenham a referência constante.', ['pisa','pisaTables','evidence']));

  const health=find('saude-recursos');
  const healthArea=areas.find(a=>a.id==='scene-saude');
  const budget=healthArea.stats[0];
  budget[0]='Dotação inicial do Ministério da Saúde';budget[1]='270,35';budget[3]='LOA 2026 · RQPC 1º quadrimestre';budget[4]='rqpc';budget[5]='Autorização inicial do órgão Ministério da Saúde, incluindo ASPS e não ASPS, conforme seu relatório de execução.';
  budget[7]='Recorte por órgão. Não equivale ao total da função Saúde no orçamento, ao financiamento das três esferas ou ao gasto pago.';
  health.tables.unshift(table('Execução federal de 2026 · Ministério da Saúde · janeiro–abril',['Etapa','R$ bilhões'],[['Dotação inicial anual','270,35'],['Dotação atualizada anual até abril','269,92'],['Empenhado até abril','119,70'],['Liquidado até abril','67,43'],['Pago até abril','63,29']], '1º RQPC 2026, quadro 4. Créditos anuais e fluxos acumulados até abril têm prazos diferentes. Não comparar quatro meses com o ano completo de 2025 como se fossem períodos iguais, nem projetar 2026 multiplicando por três. Não inclui automaticamente restos a pagar de outros exercícios.', ['rqpc']));
  health.tables.unshift(table('Financiamento federal · Ministério da Saúde · ano completo de 2025',['Etapa','R$ bilhões'],[['Dotação inicial','246,56'],['Dotação atualizada','254,15'],['Empenhado','253,12'],['Liquidado','231,50'],['Pago','227,93']], 'RAG 2025, quadro 5, Tesouro Gerencial em 12/01/2026. Total MS, ASPS + não ASPS; não inclui Anvisa/ANS. Não é o gasto de todo o SUS: estados/municípios também financiam. Etapas do mesmo recurso, não somar. Pagamentos desta execução não equivalem ao total com restos a pagar de outros anos.', ['rag']));
  health.purpose='Veja a execução federal de um ano completo e as etapas do gasto. O INCA permanece como exemplo institucional, com abrangência e período próprios.';
  health.explanation.paragraphs.unshift('Na execução federal de 2025, o pagamento corresponde a aproximadamente 89,7% da dotação atualizada do MS. A razão descreve uma etapa financeira; não mede satisfação, acesso ou eficiência. Em 2026, até abril, foram pagos R$ 63,29 bilhões sobre uma autorização anual atualizada de R$ 269,92 bilhões. Os prazos diferem: essa proporção não prova atraso ou corte anual.');
  health.explanation.sources.push('rag');
  health.conclusion='A execução nacional federal permite acompanhar compromisso, entrega verificada e pagamento. Seu volume não prova resultado clínico; o recorte do INCA ajuda a entender etapas, mas não representa todo o SUS.';
  health.sources.push('rag');
  const healthBlock=healthArea.blocks.find(b=>b.id==='saude-recursos');
  healthBlock.reading[0]=['Orçamento federal não é o financiamento total do SUS','O relatório do MS informa dotação inicial de R$ 270,35 bilhões em 2026 para o órgão. Esse recorte difere do total da função Saúde divulgado no orçamento. Estados e municípios também financiam o SUS; autorização difere de pagamento.', ['rqpc']];
  health.explanation.sources.push('rqpc');health.sources.push('rqpc');
  areas.find(a=>a.id==='scene-saude').blocks.push(topic('saude-resultados','Resultados de saúde','Mais atendimento já aparece nos resultados de saúde?', 'Confronte produção com desfechos e procure grupos que seguem em situação diferente.',[
    table('Resultados registrados no RAG · referência dezembro de cada ano',['Indicador / unidade','2024','2025'],[['Mortalidade neonatal · por mil nascidos vivos','8,42','8,25*'],['Razão de mortalidade materna · por 100 mil nascidos vivos','55,50','47,86*'],['Mortalidade infantil indígena por causas evitáveis · por mil nascidos vivos','18,41','21,84']], 'RAG 2025, quadro 30, p.42–43. * Dados preliminares, sujeitos a revisão. Populações e causas distintas: não somar, não subtrair para construir desigualdade e não compartilhar uma escala de gráfico. Registros podem ser atualizados; a comparação não é avaliação causal do programa de cirurgias.', ['rag'])
  ],text('Resultados e procedimentos têm calendários diferentes',['Os pontos estimados de mortalidade neonatal e materna diminuem; o indicador indígena de causas evitáveis aumenta. Uma média favorável não garante melhora em todos os grupos.', 'Desfechos dependem de prevenção, atenção básica, assistência, condições sociais e registro de nascimentos/óbitos. Mais procedimentos eletivos não explicam automaticamente esses indicadores; nem são necessariamente o tratamento relevante para cada causa.'],['rag']),text('Registro melhor ou mudança no atendimento?',['Aumento de notificações pode revelar casos antes ausentes; queda pode refletir melhora real, revisões de registro ou mudanças de composição. São possibilidades, sem demonstração causal neste relatório.', 'Pequenas populações podem produzir oscilações maiores; o recorte indígena exige cobertura de registro, número de eventos, território e séries mais longas. Dados preliminares precisam continuar identificados após publicação.'],['rag'],'Em aberto: causa das mudanças observadas'), 'Há movimentos diferentes entre os desfechos apresentados. Os resultados preliminares nacionais são favoráveis em dois indicadores, mas o recorte indígena alerta para desigualdade. O relatório não permite atribuir essas mudanças a uma intervenção específica.', 'Séries revisadas, cobertura dos registros, atenção pré-natal, causas evitáveis e desfechos por território; espera mediana e P90 ainda precisam de base comparável.', ['rag']));

  const ufRates=[['Acre',20.3,21.6],['Alagoas',35.4,33.1],['Amapá',45.2,42.5],['Amazonas',27.4,18.5],['Bahia',40.7,36.8],['Ceará',37.5,34.7],['Distrito Federal',9.1,9.6],['Espírito Santo',24,22],['Goiás',18.9,16.5],['Maranhão',30.3,29.7],['Mato Grosso',29.8,22.9],['Mato Grosso do Sul',19.3,20.2],['Minas Gerais',15.1,12.9],['Pará',29.5,28.4],['Paraíba',25.6,24.6],['Paraná',18.4,15.5],['Pernambuco',36.4,33],['Piauí',20.3,17.1],['Rio de Janeiro',22.1,22.6],['Rio Grande do Norte',24.4,29.1],['Rio Grande do Sul',15.2,11.3],['Rondônia',26.2,28.1],['Roraima',18.4,19.5],['Santa Catarina',8.6,7.6],['São Paulo',8.2,7.8],['Sergipe',22.8,22.1],['Tocantins',19.8,19.3]];
  const security=find('seguranca-tendencia');
  security.tables.push(table('Mortes violentas intencionais · diferenças territoriais',['Região','UFs com alta da taxa','Amplitude da taxa · 2025'],groups.map(([region,names])=>{const rs=ufRates.filter(r=>names.includes(r[0]));return [region,rs.filter(r=>r[2]>r[1]).map(r=>r[0]).join(', ')||'Nenhuma',n(Math.min(...rs.map(r=>r[2])))+' a '+n(Math.max(...rs.map(r=>r[2])))];}), 'Taxas por 100 mil habitantes, FBSP 2026, tabela 1. Amplitude entre UFs, não taxa regional. Brasil: 20,8 em 2024 → 19,1 em 2025. Sete UFs tiveram alta; 20, queda. Todas as taxas estaduais estão no detalhamento abaixo.', ['anuario']));
  security.stateTable=table('Todas as UFs · MVI por 100 mil habitantes',['UF','2024','2025'],ufRates.map(r=>r.map((v,i)=>i?n(v):v)), 'FBSP, tabela 1. Em SP, lesão corporal seguida de morte usa ocorrências como aproximação de vítimas; em MG há ajustes de categorias para evitar duplicidade com mortes por intervenção policial. Ver notas da fonte. Diferenças de registro e estimativas populacionais afetam comparabilidade.', ['anuario']);
  security.alternative.status='Contrariada: melhora em todas as UFs';
  security.alternative.paragraphs.push('A queda nacional da taxa não chegou a todas as UFs: Acre, Distrito Federal, Mato Grosso do Sul, Rio de Janeiro, Rio Grande do Norte, Rondônia e Roraima tiveram aumento. Não é correto usar só o total nacional como retrato de cada território.');
  security.conclusion+=' A taxa nacional caiu, mas sete UFs tiveram aumento. A comparação territorial impede transformar a média em resultado universal.';
  const remaining = {
    'economia-empresas': 'Em aberto: efeito dos pedidos judiciais sobre empregos',
    'economia-producao': 'Em aberto: atribuição do crescimento a uma política',
    'saude-acesso': 'Em aberto: alteração da espera nacional',
    'saude-recursos': 'Em aberto: efeito do gasto na eficiência clínica',
    'educacao-aprendizagem': 'Em aberto: contribuição de cada componente do Ideb',
    'educacao-vida': 'Não testada: progresso individual entre instrumentos distintos',
    'seguranca-riscos': 'Contrariada: melhora uniforme entre tipos de violência'
  };
  for(const [id,status] of Object.entries(remaining)) find(id).alternative.status=status;
}
